@ECHO OFF
SET TEMP=C:\TEMP
SET TMP=C:\TMP
PROMPT $V$_$D $T$_$p$g
SET DIRCMD=/O:GEN/P/A
C:\DRIVERS\DOSKEY28\DOSKEY.COM
C:\DRIVERS\CTMS21B4\BIN\CTMOUSE.EXE /3
C:\DRIVERS\DOSID251\DOSIDLE.EXE
PATH C:\DOS
GOTO %CONFIG%

:DOS_0
GOTO END

:DOS_1_SBEMU
SET BLASTER=A220 I7 D1 T6 P330 H1
C:\DRIVERS\SBEMU\JLOAD.EXE C:\DRIVERS\SBEMU\QPIEMU.DLL
C:\DRIVERS\SBEMU\HDPMI32I.EXE -r -x
C:\DRIVERS\SBEMU\SBEMU.EXE

GOTO END

:DOS_2_NET_PE3PD
GOTO NETWORK

:DOS_3_SBEMU_PE3PD
SET BLASTER=A220 I7 D1 T6 P330 H1
C:\DRIVERS\SBEMU\JLOAD.EXE C:\DRIVERS\SBEMU\QPIEMU.DLL
C:\DRIVERS\SBEMU\HDPMI32I.EXE -r -x
C:\DRIVERS\SBEMU\SBEMU.EXE
GOTO NETWORK

:NETWORK
C:\DRIVERS\PE3DRV\PKTDRV\PE3PD.COM SINT=60 LPT=1
PATH C:\DRIVERS\MTCP2023;%PATH%
SET MTCPCFG=C:\MTCP.CFG
SET TZ=UTC-8
rem dhcp
rem sntp -set sg.pool.ntp.org
GOTO END

:END
rem KEYB DV,,C:\DOS\DVORAK.SYS
